# Generated by Django 3.2.12 on 2022-03-19 17:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
            },
        ),
        migrations.CreateModel(
            name='CameraMediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Camera Media Tag',
                'verbose_name_plural': 'Camera Media Tags',
            },
        ),
        migrations.CreateModel(
            name='CameraMedia',
            fields=[
                ('_hash', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=64)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('smoke_column_class', models.CharField(blank=True, max_length=128, null=True)),
                ('geographical_direction', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cameras.camera')),
                ('tags', models.ManyToManyField(related_name='media', to='cameras.CameraMediaTag')),
            ],
            options={
                'verbose_name': 'Camera Media',
                'verbose_name_plural': 'Camera Media',
            },
        ),
    ]
