# Generated by Django 3.2.12 on 2022-03-28 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_cameramedia_cameramediatag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameramedia',
            name='geographical_direction',
            field=models.FloatField(blank=True, help_text='The geographical direction in angles of the detected fire with respect to the camera location', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='cameramedia',
            name='smoke_column_class',
            field=models.CharField(blank=True, help_text='A classification of the type of smoke detected from the camera.Possible classes are: CL1 (fires involving wood/plants), CL2 (fires involving flammable materials/liquids), CL3 (fires involving gas).', max_length=128, null=True),
        ),
    ]
