# Generated by Django 3.2.13 on 2022-05-13 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_auto_20220328_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='direction',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(360)
                ]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
