# Generated by Django 3.2.13 on 2022-05-13 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_auto_20220513_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='direction',
            field=models.FloatField(help_text='The angle of camera orientation, where 0 means North, 90 East, 180 South and 270 West', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
