# Generated by Django 3.2.13 on 2022-05-19 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_auto_20220513_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='description',
        ),
        migrations.AddField(
            model_name='camera',
            name='altitude',
            field=models.FloatField(blank=True, help_text='The altitude of the camera in meters.', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='nation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='owner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
