# Generated by Django 3.2.13 on 2022-05-19 17:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_auto_20220519_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMediaFireClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fire Class',
                'verbose_name_plural': 'Fire Classes',
            },
        ),
        migrations.RenameField(
            model_name='cameramedia',
            old_name='geographical_direction',
            new_name='direction',
        ),
        migrations.RemoveField(
            model_name='cameramedia',
            name='_hash',
        ),
        migrations.RemoveField(
            model_name='cameramedia',
            name='bounding_box',
        ),
        migrations.RemoveField(
            model_name='cameramedia',
            name='smoke_column_class',
        ),
        migrations.RemoveField(
            model_name='cameramedia',
            name='tags',
        ),
        migrations.AddField(
            model_name='cameramedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameramedia',
            name='distance',
            field=models.FloatField(blank=True, help_text='The distance in meters of the detected fire with respect to the camera location', null=True),
        ),
        migrations.AddField(
            model_name='cameramedia',
            name='is_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cameramedia',
            name='is_smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cameramedia',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cameramedia',
            name='url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='cameramedia',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='CameraMediaTag',
        ),
        migrations.AddField(
            model_name='cameramedia',
            name='fire_classes',
            field=models.ManyToManyField(blank=True, help_text='A classification of the type of smoke detected from the camera.Possible classes are: CL1 (fires involving wood/plants), CL2 (fires involving flammable materials/liquids), CL3 (fires involving gas).', related_name='media', to='cameras.CameraMediaFireClass'),
        ),
    ]
