# Generated by Django 3.2.13 on 2022-05-19 12:45

from django.db import migrations


def add_camera_media_fire_classes(apps, schema_editor):

    FireClassModel = apps.get_model("cameras", "CameraMediaFireClass")

    FIRE_CLASSES = [
        {
            "name": "CL1",
            "description": "fires involving wood/plants",
        },
        {
            "name": "CL2",
            "description": "fires involving flammable materials/liquids",
        },
        {
            "name": "CL3",
            "description": "fires involving gas",
        },
    ]
    for data in FIRE_CLASSES:
        FireClassModel.objects.get_or_create(
            name=data.pop("name"), defaults=data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_auto_20220519_1734'),
    ]

    operations = [
        migrations.RunPython(
            add_camera_media_fire_classes,
            reverse_code=migrations.RunPython.noop
        )
    ]
