# Generated by Django 3.2.13 on 2022-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_cameras_fire_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='cameramedia',
            name='is_fire',
        ),
        migrations.RemoveField(
            model_name='cameramedia',
            name='is_smoke',
        ),
        migrations.AddField(
            model_name='cameramedia',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Determines whether this media captures fire or smoke', related_name='media', to='cameras.CameraMediaTag'),
        ),
    ]
