# Generated by Django 3.2.13 on 2022-05-20 05:42

from django.db import migrations


def add_camera_media_tags(apps, schema_editor):

    TagModel = apps.get_model("cameras", "CameraMediaTag")

    TAGS = [
        {
            "name": "fire",
            "description": None,
        },
        {
            "name": "smoke",
            "description": None,
        },
    ]
    for data in TAGS:
        TagModel.objects.get_or_create(name=data.pop("name"), defaults=data)


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_auto_20220520_0542'),
    ]

    operations = [
        migrations.RunPython(
            add_camera_media_tags, reverse_code=migrations.RunPython.noop
        )
    ]
