# Generated by Django 3.2.13 on 2022-05-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_cameras_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameramedia',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
