# Generated by Django 3.2.13 on 2022-06-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0012_alter_cameramedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramedia',
            name='message',
            field=models.JSONField(blank=True, help_text='raw message content', null=True),
        ),
    ]
