# Generated by Django 3.2.13 on 2022-06-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alter_alert_media'),
        ('cameras', '0013_cameramedia_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramedia',
            name='alert',
            field=models.ForeignKey(blank=True, help_text='The alert that this camera_media might be associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_media', to='alerts.alert'),
        ),
    ]
