# Generated by Django 3.2.16 on 2023-01-10 10:27

from django.db import migrations, models
import safers.cameras.models.models_cameramedia


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0014_cameramedia_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=safers.cameras.models.models_cameramedia.camera_media_file_path),
        ),
    ]
