# Generated by Django 4.2 on 2023-05-29 10:04

from django.db import migrations, models
import safers.cameras.models.models_cameramedia


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0017_rename_file_cameramedia_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=safers.cameras.models.models_cameramedia.camera_media_file_path),
        ),
        migrations.AlterField(
            model_name='cameramedia',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], help_text='What type of media is this?', max_length=64),
        ),
    ]
