# Generated by Django 3.2.12 on 2022-04-26 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGeometry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='notifications.notification')),
            ],
        ),
    ]
