# Generated by Django 3.2.12 on 2022-05-05 17:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bounding_box',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='notification',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='notification',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificationgeometry',
            name='_hash',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationgeometry',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
