# Generated by Django 3.2.12 on 2022-05-11 12:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20220505_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationgeometry',
            options={'verbose_name': 'Notification Geometry', 'verbose_name_plural': 'Notification Geometries'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='certainty',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='urgency',
        ),
        migrations.AddField(
            model_name='notification',
            name='geometry_collection',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(blank=True, choices=[('REPORT', 'Report (from chatbot)'), ('EFFIS_FWI', 'FWI (from netCDF)')], max_length=128, null=True),
        ),
    ]
