# Generated by Django 3.2.15 on 2022-09-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
