# Generated by Django 3.2.15 on 2022-09-29 09:56

from django.db import migrations


def update_countries(apps, schema_editor):

    NotificationModel = apps.get_model("notifications", "Notification")
    CountryModel = apps.get_model("core", "Country")

    for notification in NotificationModel.objects.all():
        if notification.center:
            country = CountryModel.objects.filter(
                geometry__intersects=notification.center
            ).first()
            notification.country = country.admin_name if country else None
            notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_country'),
    ]

    operations = [
        migrations.RunPython(
            update_countries, reverse_code=migrations.RunPython.noop
        ),
    ]
