# Generated by Django 3.2.15 on 2022-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220921_1413'),
        ('notifications', '0010_notification_country_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='restriction',
            field=models.CharField(blank=True, choices=[('Citizen', 'Citizen'), ('Professional', 'Professional'), ('Organization', 'Organization')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_organizations',
            field=models.ManyToManyField(related_name='targeted_notifications', to='users.Organization'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scope',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Restricted', 'Restricted')], max_length=128, null=True),
        ),
    ]
