version: "3"

services:

  safers-db:
    image: kartoza/postgis:latest
    environment:
      POSTGRES_DBNAME: safers_db
      POSTGRES_USER: safers_user
      POSTGRES_PASS: safers_pwd
      ALLOW_IP_RANGE: 0.0.0.0/0
    networks:
      - safers
    ports:
      - "5666:5432"

  safers-auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: fusionauth_user
      POSTGRES_PASSWORD: fusionauth_pwd
    healthcheck:
      test: "pg_isready -U fusionauth_user"
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - safers
    restart: unless-stopped

  safers-auth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      safers-auth-db:
        condition: service_healthy
    env_file:
      - ./auth/.env
    environment:
      DATABASE_URL: jdbc:postgresql://safers-auth-db:5432/fusionauth
      DATABASE_ROOT_USERNAME: fusionauth_user
      DATABASE_ROOT_PASSWORD: fusionauth_pwd
      DATABASE_USERNAME: fusionauth_user
      DATABASE_PASSWORD: fusionauth_pwd
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
    restart: unless-stopped
    volumes:
      - ./auth/config:/usr/local/fusionauth/confg
      - ./auth/kickstart:/usr/local/fusionauth/kickstart
    networks:
      - safers
    ports:
      - "9011:9011"

  # safers-broker:
  #   image: rabbitmq:3-management
  #   hostname: broker
  #   # TODO: WILL WANT SOME CONFIG IN DEFINITIONS TO SETUP QUEUES
  #   # TODO: BUT NOT PWDS, ETC
  #   # volumes:
  #   #   - ./broker/etc/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
  #   #   - ./broker/etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  #   #   - ./broker/db:/var/lib/rabbitmq/mnesia/rabbit@safers
  #   #   - ./broker/logs:/var/log/rabbitmq/log
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=safers_user
  #     - RABBITMQ_DEFAULT_PASS=safers_pwd
  #   networks:
  #     - safers
  #   ports:
  #     - 5672:5672  # internal queue
  #     - 15672:15672  # management client

  safers-server:
    build:
      context: .
    tty: true
    env_file:
      - .env
    environment:
      DJANGO_ENVIRONMENT: development
      DJANGO_SETTINGS_MODULE: config.settings
      ENABLE_DJANGO: 1
    working_dir: /home/app/server
    volumes:
      - ./server:/home/app/server
    networks:
      - safers
    ports:
      - "8000:8000" # API
      - "8080:8080" # profiling

  safers-worker:
    build: .
    tty: true
    env_file:
      - .env
    environment:
      DJANGO_ENVIRONMENT: development
      DJANGO_SETTINGS_MODULE: config.settings
      ENABLE_RMQ_WORKER: 1
    volumes:
      - ./server:/home/app/server
    networks:
      - safers

  safers-scheduler:
    build: .
    env_file:
      - .env
    environment:
      DJANGO_ENVIRONMENT: development
      DJANGO_SETTINGS_MODULE: config.settings
      ENABLE_CRON: 1
    volumes:
      - ./server:/home/app/server
      - ./scheduler:/home/app/scheduler
    networks:
      - safers

networks:
  safers:
    name: safers
    driver: bridge
