# Generated by Django 3.2.12 on 2022-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_accepted_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_password',
            field=models.BooleanField(default=False, help_text='Force user to change password at next login.'),
        ),
    ]
