# Generated by Django 3.2.12 on 2022-03-15 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220310_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User (oauth2)',
                'verbose_name_plural': 'Users (oauth2)',
            },
        ),
    ]
