# Generated by Django 3.2.12 on 2022-03-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aois', '0002_aoi'),
        ('users', '0010_oauth2user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_aoi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='aois.aoi'),
        ),
    ]
