# Generated by Django 3.2.12 on 2022-03-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20220319_1012'),
        ('users', '0012_local_vs_remote_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_alerts',
            field=models.ManyToManyField(related_name='favorited_users', to='alerts.Alert'),
        ),
    ]
