# Generated by Django 3.2.12 on 2022-03-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
        ('users', '0013_user_favorite_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_events',
            field=models.ManyToManyField(related_name='favorited_users', to='events.Event'),
        ),
    ]
