# Generated by Django 3.2.12 on 2022-03-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_cameramedia_cameramediatag'),
        ('users', '0014_user_favorite_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_camera_medias',
            field=models.ManyToManyField(related_name='favorited_users', to='cameras.CameraMedia'),
        ),
    ]
