# Generated by Django 3.2.12 on 2022-03-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220324_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_token_key',
            field=models.TextField(blank=True, help_text='TODO: THIS IS A SECURITY RISK; REMOVE IN PRODUCTION', null=True),
        ),
    ]
