# Generated by Django 3.2.12 on 2022-03-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_active_token_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauth2user',
            options={'verbose_name': 'OAuth2 User Data', 'verbose_name_plural': 'OAuth2 User Data'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
