# Generated by Django 3.2.12 on 2022-03-25 18:39

from django.db import migrations


def create_profiles_for_existing_users(apps, schema_editor):

    UserModel = apps.get_model("users", "User")
    UserProfile = apps.get_model("users", "UserProfile")

    for user in UserModel.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220325_0930'),
    ]

    operations = [
        migrations.RunPython(
            create_profiles_for_existing_users,
            reverse_code=migrations.RunPython.noop
        ),
    ]
