# Generated by Django 3.2.15 on 2022-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userprofile_data_migration2'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_id',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
