# Generated by Django 3.2.15 on 2022-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_organization_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='label',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_id',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
