# Generated by Django 4.2 on 2023-05-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_organization_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
