# Generated by Django 4.2 on 2023-05-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.JSONField(default=dict, help_text='JSON representation of profile; used for synchronization w/ gateway.'),
        ),
    ]
