# Generated by Django 4.2 on 2023-05-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_user_first_name_and_last_name_add_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
