# Generated by Django 4.2 on 2023-05-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_user_organization_remove_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': False},
        ),
    ]
