# Generated by Django 4.2 on 2023-05-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_organization_name_user_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_token_key',
        ),
    ]
