# Generated by Django 4.2 on 2023-05-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_delete_oauth2user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', help_text='What stage of registration is this user at?', max_length=64),
        ),
    ]
