# Generated by Django 4.2 on 2023-06-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('LEGACY', 'Legacy')], default='PENDING', help_text='What stage of registration is this user at?', max_length=64),
        ),
    ]
