# Generated by Django 3.2.12 on 2022-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(help_text='The numerical ID of the desired Tweet from Twitter.'),
        ),
    ]
