# Generated by Django 3.2.12 on 2022-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
