# Generated by Django 3.2.12 on 2022-03-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_tweet_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='SocialEvent',
        ),
        migrations.AlterModelOptions(
            name='socialevent',
            options={'verbose_name': 'Social Event', 'verbose_name_plural': 'Social Events'},
        ),
    ]
