# Generated by Django 3.2.12 on 2022-03-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_socialevent_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialevent',
            old_name='type',
            new_name='severity',
        ),
    ]
