# Generated by Django 3.2.13 on 2022-05-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tmp_geometry',
            new_name='geometry',
        ),
    ]
