# Generated by Django 3.2.12 on 2022-03-18 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aois', '0002_aoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='aoi',
            name='midpoint',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='aoi',
            name='zoom_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
