# Generated by Django 3.2.12 on 2022-03-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aois', '0003_auto_20220318_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aoi',
            options={'ordering': ['country', 'name'], 'verbose_name': 'AOI', 'verbose_name_plural': 'AOIs'},
        ),
    ]
