# Generated by Django 3.2.12 on 2022-03-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordCounter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_results.chordcounter',),
        ),
        migrations.CreateModel(
            name='ClockedSchedule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.clockedschedule',),
        ),
        migrations.CreateModel(
            name='CrontabSchedule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.crontabschedule',),
        ),
        migrations.CreateModel(
            name='GroupResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_results.groupresult',),
        ),
        migrations.CreateModel(
            name='IntervalSchedule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.intervalschedule',),
        ),
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='PeriodicTasks',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.periodictasks',),
        ),
        migrations.CreateModel(
            name='SolarSchedule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.solarschedule',),
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_results.taskresult',),
        ),
    ]
