# Generated by Django 3.2.12 on 2022-03-26 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_chordcounter_clockedschedule_crontabschedule_groupresult_intervalschedule_periodictask_periodictasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128)),
                ('app_id', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('delivery_mode', models.CharField(default='persistent', max_length=128)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MessageBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype_id', models.IntegerField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='tasks.message')),
            ],
        ),
    ]
