from django.conf import settings


def backup_filename_template(
    project, databasename, servername, datetime, extension, content_type
):
    """
    Configures the name of the output files generated by django-dbbackup.  Notice the
    1st argument is passed in via the `partial` function in "config/settings/base.py"
    """
    return f"{project}_{content_type}_{datetime}.{extension}"
