# Generated by Django 3.2.12 on 2022-04-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_dataresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype_id', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=128, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=128, null=True)),
                ('format', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DataType',
                'verbose_name_plural': 'DataTypes',
            },
        ),
    ]
