# Generated by Django 3.2.12 on 2022-04-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_datatype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataResource',
            new_name='DataLayer',
        ),
        migrations.AlterModelOptions(
            name='datalayer',
            options={'verbose_name': 'Data Layer', 'verbose_name_plural': 'Data Layers'},
        ),
    ]
