# Generated by Django 3.2.13 on 2022-05-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20220406_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='datatype_id',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='description',
            field=models.TextField(blank=True, help_text='This is what should appear in the info icon of the dashboard.', null=True),
        ),
        migrations.AddConstraint(
            model_name='datatype',
            constraint=models.UniqueConstraint(fields=('datatype_id', 'group', 'subgroup'), name='unique_data_layer_and_category'),
        ),
        migrations.AddConstraint(
            model_name='datatype',
            constraint=models.CheckConstraint(check=models.Q(('datatype_id__isnull', False), ('subgroup__isnull', False), ('group__isnull', False), _connector='OR'), name='required_data_layer_and_category'),
        ),
    ]
