# Generated by Django 3.2.13 on 2022-06-27 15:08

from django.db import migrations


def add_data_type_sources(apps, schema_editor):

    DataTypeModel = apps.get_model("data", "DataType")

    for data_type in DataTypeModel.objects.all():
        data_type_extra_info = data_type.extra_info
        if data_type_extra_info:
            data_type_source = data_type_extra_info.get("Responsible", None)
            if data_type_source is not None and data_type.source is None:
                data_type.source = data_type_source.upper()
                data_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_datatype_source'),
    ]

    operations = [
        migrations.RunPython(
            add_data_type_sources, reverse_code=migrations.RunPython.noop
        )
    ]
