# Generated by Django 3.2.13 on 2022-06-28 08:46

from django.db import migrations


def add_data_type_domains(apps, schema_editor):

    DataTypeModel = apps.get_model("data", "DataType")

    for data_type in DataTypeModel.objects.all():
        data_type_group = data_type.group
        if data_type_group is not None and data_type.domain is None:
            data_type.domain = data_type_group.title()
            data_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_datatype_domain'),
    ]

    operations = [
        migrations.RunPython(
            add_data_type_domains, reverse_code=migrations.RunPython.noop
        )
    ]
