# Generated by Django 3.2.13 on 2022-06-30 15:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_datatype_domain_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapRequest',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.CharField(default='PROCESSING', max_length=64)
                ),
                ('parameters', models.JSONField(blank=True, default=dict)),
                (
                    'geometry',
                    django.contrib.gis.db.models.fields.GeometryCollectionField(
                        srid=4326
                    )
                ),
                (
                    'data_types',
                    models.ManyToManyField(
                        related_name='map_requests', to='data.DataType'
                    )
                ),
            ],
            options={
                'verbose_name': 'Map Request',
                'verbose_name_plural': 'Map Reqeusts',
            },
        ),
    ]
