# Generated by Django 3.2.13 on 2022-07-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_maprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='is_on_demand',
            field=models.BooleanField(default=False),
        ),
    ]
