# Generated by Django 3.2.13 on 2022-07-01 09:54

from django.db import migrations


def add_data_type_is_on_demand(apps, schema_editor):

    DataTypeModel = apps.get_model("data", "DataType")

    for data_type in DataTypeModel.objects.all():
        data_type_extra_info = data_type.extra_info
        if data_type_extra_info:
            data_type_is_on_demand = (
                data_type_extra_info.get("Update frequency") == "on demand"
            )
            if data_type_is_on_demand != data_type.is_on_demand:
                data_type.is_on_demand = data_type_is_on_demand
                data_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_datatype_is_on_demand'),
    ]

    operations = [
        migrations.RunPython(
            add_data_type_is_on_demand, reverse_code=migrations.RunPython.noop
        )
    ]
