# Generated by Django 3.2.13 on 2022-07-01 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0013_datatype_is_on_demand_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User that issued the MapRequest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
