# Generated by Django 3.2.13 on 2022-07-05 09:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_maprequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprequest',
            name='geometry_wkt',
            field=models.TextField(blank=True, help_text='WKT representation of geometry', null=True),
        ),
        migrations.AlterField(
            model_name='maprequest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
