# Generated by Django 3.2.13 on 2022-07-05 11:01

from django.db import migrations, models
import safers.data.models.models_maprequests


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_maprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maprequest',
            name='request_id',
            field=models.CharField(default=safers.data.models.models_maprequests.get_next_request_id, max_length=255),
        ),
    ]
