# Generated by Django 3.2.14 on 2022-07-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_maprequest_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maprequest',
            name='data_types',
        ),
    ]
