# Generated by Django 3.2.14 on 2022-07-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_remove_maprequest_data_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maprequest',
            name='status',
        ),
        migrations.CreateModel(
            name='MapRequestDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, choices=[('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('AVAILABLE', 'Available')], max_length=64, null=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.datatype')),
                ('map_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.maprequest')),
            ],
        ),
        migrations.AddField(
            model_name='maprequest',
            name='data_types',
            field=models.ManyToManyField(related_name='map_requests', through='data.MapRequestDataType', to='data.DataType'),
        ),
    ]
