# Generated by Django 3.2.14 on 2022-07-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20220714_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maprequestdatatype',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_request_data_types', to='data.datatype'),
        ),
        migrations.AlterField(
            model_name='maprequestdatatype',
            name='map_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_request_data_types', to='data.maprequest'),
        ),
    ]
