# Generated by Django 3.2.14 on 2022-08-02 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20220715_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprequestdatatype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maprequestdatatype',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
