# Generated by Django 3.2.15 on 2022-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20220802_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprequestdatatype',
            name='message',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
