# Generated by Django 3.2.15 on 2022-09-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_maprequestdatatype_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='group_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
