# Generated by Django 3.2.15 on 2022-09-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_maprequest_geometry_extent_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maprequest',
            name='geometry_extent',
        ),
    ]
