# Generated by Django 3.2.15 on 2022-09-26 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_remove_maprequest_geometry_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprequest',
            name='geometry_extent',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                blank=True,
                default=list,
                help_text='extent of bbox of geometry as a list',
                size=None
            ),
        ),
        migrations.AddField(
            model_name='maprequest',
            name='geometry_extent_str',
            field=models.CharField(
                max_length=256,
                blank=True,
                help_text='extent of bbox of geometry as a string',
                null=True
            ),
        ),
    ]
