# Generated by Django 3.2.15 on 2022-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_map_request_geometry_extent_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprequest',
            name='geometry_features',
            field=models.JSONField(blank=True, help_text='FeatureCollection representation of geometry', null=True),
        ),
    ]
