# Generated by Django 3.2.15 on 2022-10-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_mapreqeust_geometry_features_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprequest',
            name='restrict_data_to_aoi',
            field=models.BooleanField(
                default=False,
                help_text=
                "whether to treat geometry as a bbox or to ignore it and use the user's defaut_aoi as the bbox"
            ),
        ),
    ]
