# Generated by Django 3.2.15 on 2022-10-07 15:25

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_maprequest_restrict_data_to_aoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprequest',
            name='geometry_buffer_size',
            field=models.FloatField(default=0, help_text='area (in kilometers) to increase the geometry by when rendering the layer.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='maprequest',
            name='geometry_buffered_extent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, help_text='extent of bbox of geometry plus buffer as a list', size=None),
        ),
        migrations.AddField(
            model_name='maprequest',
            name='geometry_buffered_extent_str',
            field=models.CharField(blank=True, help_text='extent of bbox of geometry plus buffer as a string', max_length=256, null=True),
        ),
    ]
