# Generated by Django 3.2.15 on 2022-10-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20221007_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maprequest',
            name='restrict_data_to_aoi',
        ),
    ]
