# Generated by Django 3.2.16 on 2023-01-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_remove_maprequest_restrict_data_to_aoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='feature_string',
            field=models.TextField(blank=True, help_text='format string to use when rendering output from GetFeatureInfo', null=True),
        ),
    ]
