# Generated by Django 3.2.16 on 2023-02-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_datatype_feature_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={'ordering': ('datatype_id',), 'verbose_name': 'DataType', 'verbose_name_plural': 'DataTypes'},
        ),
    ]
