# Generated by Django 3.2.12 on 2022-03-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafersSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow users to register w/ Safers.')),
            ],
            options={
                'verbose_name': 'Safers Settings',
                'verbose_name_plural': 'Safers Settings',
            },
        ),
    ]
