# Generated by Django 3.2.12 on 2022-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saferssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='require_verification',
            field=models.BooleanField(default=True, help_text='Require an email verification step to the sign up process.'),
        ),
    ]
