# Generated by Django 3.2.12 on 2022-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saferssettings_require_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='require_terms_acceptance',
            field=models.BooleanField(default=True, help_text='Require a user to accept the terms & conditions during the sign up process.'),
        ),
    ]
