# Generated by Django 3.2.12 on 2022-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_saferssettings_require_terms_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='max_favorite_alerts',
            field=models.PositiveBigIntegerField(default=3, help_text="Number of alerts that a user can mark as 'favorite'."),
        ),
    ]
