# Generated by Django 3.2.12 on 2022-03-10 14:38

from django.db import migrations


def create_admin_group(apps, schema_editor):

    GroupModel = apps.get_model("auth", "Group")

    group, _ = GroupModel.objects.get_or_create(name="AdminGroup")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_saferssettings_max_favorite_events'),
    ]

    operations = [
        migrations.RunPython(
            create_admin_group, reverse_code=migrations.RunPython.noop
        )
    ]
