# Generated by Django 3.2.12 on 2022-03-10 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_admin_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='possible_event_distance',
            field=models.FloatField(default=10.0, help_text='Radius (in kms) within which alerts can be transformed into events', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='saferssettings',
            name='possible_event_timerange',
            field=models.FloatField(default=72.0, help_text='Time range (in hours) within which alerts can be transformed into events', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
    ]
