# Generated by Django 3.2.12 on 2022-03-16 23:53

import django.core.validators
from django.db import migrations, models
import safers.core.models.models_documents


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220310_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=safers.core.models.models_documents.document_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), safers.core.models.models_documents.FileSizeValidator(16)])),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_name_version'),
        ),
    ]
