# Generated by Django 3.2.12 on 2022-03-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documentagreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='max_favorite_camera_media',
            field=models.PositiveBigIntegerField(default=3, help_text="Number of camera_medias that a user can mark as 'favorite'."),
        ),
    ]
