# Generated by Django 3.2.12 on 2022-05-06 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_saferssettings_default_timerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='polling_frequency',
            field=models.FloatField(default=60, help_text='The frequency (in seconds) that the frontend should poll the backend for new data.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
