# Generated by Django 3.2.12 on 2022-05-12 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_saferssettings_polling_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='request_timeout',
            field=models.FloatField(default=6000, help_text='The time (in milliseconds) for the frontend to wait for a response from the backend. Set to 0 to have no timeout.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
