# Generated by Django 3.2.13 on 2022-07-01 12:47

from django.db import migrations


def add_existing_site_profiles(apps, schema_editor):

    SiteModel = apps.get_model("sites", "Site")
    SiteProfileModel = apps.get_model("core", "SiteProfile")

    for site in SiteModel.objects.all():
        SiteProfileModel.objects.get_or_create(site=site)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_siteprofile'),
    ]

    operations = [
        migrations.RunPython(
            add_existing_site_profiles, reverse_code=migrations.RunPython.noop
        )
    ]
