# Generated by Django 3.2.15 on 2022-09-09 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='camera_media_preserve_timerange',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='Time range of (non smoke/fire) camera_medias to preserve; everything outside of this range is purged.'),
        ),
    ]
