# Generated by Django 3.2.15 on 2022-09-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_saferssettings_camera_media_preserve_timerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='restrict_data_to_aoi',
            field=models.BooleanField(default=False, help_text="Always resize DataLayers to the user's AOI, regardless of either the map viewport or the full extent of the DataLayer."),
        ),
    ]
