# Generated by Django 3.2.15 on 2022-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_saferssettings_restrict_data_to_aoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='allow_password_change',
            field=models.BooleanField(default=False, help_text='Allow users to change their password via the dashboard.'),
        ),
    ]
