# Generated by Django 3.2.15 on 2022-10-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_saferssettings_allow_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='map_request_resolution',
            field=models.PositiveIntegerField(default=512, help_text='The resolution (ie: height x width) to use for MapRequests.'),
        ),
    ]
