# Generated by Django 3.2.16 on 2022-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_saferssettings_map_request_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='geoserver_standard',
            field=models.CharField(
                choices=[('WMS', 'WMS'), ('WMTS', 'WMTS')],
                default='WMTS',
                help_text='Whether to use tiled (WMTS) or non-tiled data (WMS).',
                max_length=32
            ),
        ),
    ]
