# Generated by Django 3.2.16 on 2023-02-09 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_saferssettings_geoserver_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='camera_media_trigger_alert_timerange',
            field=models.DurationField(default=datetime.timedelta(seconds=21600), help_text='Time range between successive smoke/fire camera_medias that will trigger an alert.'),
        ),
    ]
