# Generated by Django 3.2.17 on 2023-02-26 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_saferssettings_camera_media_trigger_alert_timerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saferssettings',
            name='camera_media_trigger_alert_timerange',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Time range between successive smoke/fire camera_medias that will trigger an alert.'),
        ),
    ]
