# Generated by Django 4.2 on 2023-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_saferssettings_camera_media_trigger_alert_timerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saferssettings',
            name='allow_local_signin',
        ),
        migrations.RemoveField(
            model_name='saferssettings',
            name='allow_remote_signin',
        ),
        migrations.RemoveField(
            model_name='saferssettings',
            name='require_verification',
        ),
        migrations.AddField(
            model_name='saferssettings',
            name='allow_signin',
            field=models.BooleanField(default=True, help_text='Allow users to signin w/ the dashboard.'),
        ),
        migrations.AlterField(
            model_name='saferssettings',
            name='allow_signup',
            field=models.BooleanField(default=True, help_text='Allow users to register w/ the dashboard.'),
        ),
    ]
