# Generated by Django 4.2 on 2023-05-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_saferssettings_allow_local_signin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saferssettings',
            name='geoserver_standard',
        ),
        migrations.RemoveField(
            model_name='saferssettings',
            name='map_request_resolution',
        ),
        migrations.RemoveField(
            model_name='saferssettings',
            name='restrict_data_to_aoi',
        ),
    ]
