# Generated by Django 4.2 on 2023-05-26 13:06

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0027_remove_saferssettings_geoserver_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='admin_notice_color',
            field=colorfield.fields.ColorField(default='#CCCCCC', help_text='Color of site-specific notice in the Admin.', image_field=None, max_length=18, samples=[('#CCCCCC', 'Grey'), ('#009933', 'Green'), ('#FFAA00', 'Yellow'), ('#FF0000', 'Red')]),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_admin_notice',
            field=models.BooleanField(default=False, help_text='Whether or not to show a site-specific notice in the Admin.'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code to identify this site (to RMQ).', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Description of site.', null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='site',
            field=models.OneToOneField(help_text='Associated site.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sites.site'),
        ),
    ]
