# Generated by Django 4.2 on 2023-05-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_siteprofile_admin_notice_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='allow_remote_deletion',
            field=models.BooleanField(default=False, help_text='When deleting a user from the dashboard also delete a user from all of safers.'),
        ),
    ]
