# Generated by Django 4.2.2 on 2023-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_saferssettings_allow_remote_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='profile',
            field=models.BooleanField(default=False, help_text='Enable silk profiling on API Views.'),
        ),
    ]
