# Generated by Django 4.2.2 on 2023-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_saferssettings_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='display_dashboard_notifications',
            field=models.BooleanField(default=True, help_text='Display the top panel of the general dashboard.'),
        ),
    ]
