# Generated by Django 4.2.2 on 2023-07-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_saferssettings_display_dashboard_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferssettings',
            name='display_menu_notifications',
            field=models.BooleanField(default=True, help_text='Display the notification icons on the sidebar menu.'),
        ),
    ]
