# Generated by Django 3.2.13 on 2022-05-30 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rmq', '0004_auto_20220524_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is the timestamp that the message was sent, NOT the timestamp of the artefact being messaged about (that is likely to be found in the message body).'),
        ),
    ]
