# Generated by Django 3.2.12 on 2022-05-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='_hash',
        ),
    ]
