# Generated by Django 3.2.12 on 2022-05-10 11:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event__hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geometry',
        ),
        migrations.AddField(
            model_name='event',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='event',
            name='geometry_collection',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
    ]
