# Generated by Django 3.2.15 on 2022-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220513_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sequence_number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
