# Generated by Django 3.2.14 on 2022-08-05 08:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userprofile_data_migration2'),
        ('chatbot', '0003_auto_20220514_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_id', models.CharField(max_length=128, unique=True)),
                ('start', models.DateTimeField()),
                ('start_inclusive', models.BooleanField()),
                ('end', models.DateTimeField()),
                ('end_inclusive', models.BooleanField()),
                ('source', models.CharField(choices=[('Chatbot', 'Chatbot')], default='Chatbot', max_length=64)),
                ('scope', models.CharField(choices=[('Public', 'Public'), ('Restricted', 'Restricted')], default='Public', max_length=64)),
                ('restriction', models.CharField(choices=[('Citizen', 'Citizen'), ('Professional', 'Professional'), ('Organization', 'Organization'), ('None', 'None')], default='None', max_length=64)),
                ('message', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('source_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_communications', to='users.organization')),
                ('target_organizations', models.ManyToManyField(related_name='targeted_chatbot_communications', to='users.Organization')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
            },
        ),
    ]
