# Generated by Django 3.2.15 on 2022-08-16 12:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import safers.chatbot.models.models_missions


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_id', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('organization', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('start_inclusive', models.BooleanField()),
                ('end', models.DateTimeField()),
                ('end_inclusive', models.BooleanField()),
                ('source', models.CharField(choices=[('Chatbot', 'Chatbot')], default='Chatbot', max_length=64)),
                ('status', models.CharField(blank=True, choices=[('Created', 'Created'), ('TakenInCharge', 'Taken In Charge'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], max_length=64, null=True)),
                ('reports', models.JSONField(blank=True, default=dict, validators=[safers.chatbot.models.models_missions.validate_reports])),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
    ]
