# Generated by Django 3.2.15 on 2022-08-22 13:24

import django.contrib.postgres.fields
from django.db import migrations, models
import safers.chatbot.models.models_reports


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20220816_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('hazard', models.CharField(blank=True, max_length=128, null=True)),
                ('target_key', models.CharField(blank=True, max_length=128, null=True)),
                ('target', models.CharField(blank=True, max_length=128, null=True)),
                ('group', models.CharField(blank=True, max_length=128, null=True)),
                ('group_key', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_group', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_group_key', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('group_code', models.CharField(blank=True, max_length=128, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=128, null=True)),
                ('min_value', models.CharField(blank=True, max_length=128, null=True)),
                ('max_value', models.CharField(blank=True, max_length=128, null=True)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Report Category',
                'verbose_name_plural': 'Report Categories',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='categories',
            field=models.JSONField(default=list, validators=[safers.chatbot.models.models_reports.validate_categories]),
        ),
    ]
