# Generated by Django 3.2.15 on 2022-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20220816_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='activity',
            field=models.CharField(blank=True, choices=[('Surveillance', 'Surveillance'), ('In activity in operative centers', 'In activity in operative centers'), ('AIB Modules', 'AIB Modules'), ('Mobile tubs', 'Mobile tubs'), ('Powered equip.', 'Powered equip.'), ('Manual equip.', 'Manual equip.'), ('Pumping equip.', 'Pumping equip.'), ('Barriers', 'Barriers'), ('Operative machines', 'Operative machines'), ('Assistance to the population', 'Assistance to the population'), ('Fire ext. system', 'Fire ext. system'), ('Fuel reduction', 'Fuel reduction'), ('Fire suppression', 'Fire suppression'), ('Impact assessment', 'Impact assessment'), ('Restoration', 'Restoration'), ('Evacuation', 'Evacuation'), ('Search and rescue', 'Search and rescue'), ('Rubble removal', 'Rubble removal'), ('Search missing', 'Search missing')], max_length=128, null=True),
        ),
    ]
