# Generated by Django 3.2.15 on 2022-08-23 12:20

from django.db import migrations, models
import safers.chatbot.models.models_communications


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_action_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='assigned_to',
            field=models.JSONField(default=list, validators=[safers.chatbot.models.models_communications.validate_assigned_to]),
        ),
    ]
