# Generated by Django 3.2.15 on 2022-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
