# Generated by Django 3.2.15 on 2022-08-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_auto_20220829_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='end_inclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='start_inclusive',
            field=models.BooleanField(default=True),
        ),
    ]
