# Generated by Django 3.2.15 on 2022-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_auto_20220923_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Taken In Charge', 'Taken In Charge'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], default='Created', max_length=64),
        ),
    ]
