# Generated by Django 3.2.16 on 2023-02-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_alter_action_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcategory',
            options={'ordering': ('category_id',), 'verbose_name': 'Report Category', 'verbose_name_plural': 'Report Categories'},
        ),
    ]
