# Generated by Django 3.2.12 on 2022-05-02 09:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20220319_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='_hash',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='bounding_box',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='geometry',
        ),
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='certainty',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='event',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.JSONField(blank=True, help_text='raw message content', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='scope',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(blank=True, choices=[('UNVALIDATED', 'Unvalidated'), ('VALIDATED', 'Validated'), ('POSSIBLE_EVENT', 'Possible Event')], default='UNVALIDATED', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='urgency',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='AlertGeometry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='alerts.alert')),
            ],
        ),
    ]
