# Generated by Django 3.2.12 on 2022-05-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20220505_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='information',
            field=models.TextField(blank=True, help_text='additional information added by dashboard user', null=True),
        ),
    ]
