# Generated by Django 3.2.12 on 2022-05-10 10:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='geometry_collection',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
    ]
