# Generated by Django 3.2.12 on 2022-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alert_geometry_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, choices=[('REPORT', 'Report (from chatbot)'), ('EFFIS_FWI', 'FWI (from netCDF)')], max_length=128, null=True),
        ),
    ]
