# Generated by Django 3.2.13 on 2022-05-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alter_alert_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, choices=[('REPORT', 'Report (from chatbot)'), ('EFFIS_FWI', 'FWI (from netCDF)'), ('IN SITU CAMERAS', 'In-Situ Cameras')], max_length=128, null=True),
        ),
    ]
