# Generated by Django 3.2.13 on 2022-05-31 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alter_alert_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=512), blank=True, default=list, size=None),
        ),
    ]
