# Generated by Django 3.2.15 on 2022-09-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alter_alert_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='sequence_number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
