# Generated by Django 3.2.15 on 2022-09-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alert_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, choices=[('DSS', 'Decision Support System'), ('IN SITU CAMERAS', 'In-Situ Cameras')], max_length=128, null=True),
        ),
    ]
