# Generated by Django 4.2 on 2023-06-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_saferssettings_allow_remote_deletion'),
        ('alerts', '0013_alert_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
