# Generated by Django 4.2.2 on 2023-09-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alter_alert_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='media',
        ),
    ]
