# Generated by Django 4.2.2 on 2023-09-05 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alter_alert_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='media',
            new_name='media_urls',
        ),
        migrations.AddField(
            model_name='alert',
            name='thumbnail_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=512), blank=True, default=list, size=None),
        ),
    ]
